name: Despliegue en el Servidor

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15]

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Despliegue en el servidor
        run: |
          ssh sysadmin@209.145.61.41 'cd /var/www/html/grp-portal && git pull origin master && npm run build:prod '
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
